# Pull Request - Trabajo Práctico: Sistema de Gestión de Biblioteca con Spring Framework

## Descripción

  ## Cambios realizados
-
-
-

## Issue relacionado
  Closes #

  ## Milestone
  Milestone: `Etapa X - ...`

  ## Checklist de verificación

  - [ ] La funcionalidad implementada cumple con la consigna
  - [ ] El código compila correctamente
  - [ ] El código fue probado desde `Main` u otra clase de prueba
  - [ ] Este PR está asociado a un Issue con milestone y project
  - [ ] Se siguieron los principios SOLID correspondientes
  - [ ] El código fue revisado por otro miembro del equipo (si aplica)
